global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "app"
    metrics_path: /metrics
    static_configs:
      - targets: ["46.146.248.104:8042"]  # приложение

  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["46.146.248.104:9100"]  # node exporter / железо

  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["46.146.248.104:8080"]  # cAdvisor / контейнеры