global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.104:9100"]  # node exporter / железо

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.104:8080"]  # cAdvisor / контейнеры