global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.104:9100"]  # node exporter / железо

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.104:8080"]  # cAdvisor / контейнеры
  
  - job_name: "postgres"
    static_configs:
      - targets: ["192.168.0.104:9187"]  # PostgreSQL node exporter

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    metrics_path: /metrics
    scrape_interval: 30s
